### ISSUE TITLE
Sequential Download and Video Streaming

### ISSUE THREAD

**Issue by ravaan** [pskopnik/adcl#1]
Is there a sequential download option available for ADC protocol?

I also wanted to ask whether there is a way to directly stream a TTH/Magnet of a file from an ADC Hub, wasn't able to find any implementation online as of yet.

I was working on making a streaming service on top of the DC network we have on our campus.

**Comment by seoester** [comment]
Thanks for your interest, I am not sure what you mean when talking about "sequential download", perhaps you can elaborate.

There is no way of streaming a file from an ADC Hub: The hub essentially only functions as a message broker and trusted authority shared by the clients. To stream a file, you have to connect to a client (CTM / RCM) with the file in question (either do a search (SCH) or keep an index of all files currently in the network) and request a download then (GET).

If you're planning to work with ADC, I recommend reading the specification in its entirety (and perhaps the extensions) and also have a look at some actual communications (most visual clients have functionality to keep a log of all sent / received messages).

Your application use case sounds interesting, I was working on some similar ideas. Drop me a mail if you'd like to throw around some ideas :)
